/*
** execute/epilogue.sail: close scattered defs, helpers
** See Copyright Notice in LICENSE.txt
*/

/* -------------------------------------------------------------------------- */
/* -- Close scattered defs -------------------------------------------------- */

end execute

/* -------------------------------------------------------------------------- */
/* -- El Fin (execute/epilogue.sail) ---------------------------------------- */
